title: Thiago F. Lins
# description: Hanuman is a minimal yet powerful Jekyll theme for your blogs and websites.
# cover: assets/images/radhakrishna.jpg
# logo: assets/images/logo.png
favicon: assets/images/favicon.jpg
imagecover: assets/images/me-playing.jpg
baseurl: "" # the subpath of your site, e.g. /blog/ or / for root
url: "http://thiagoflins.com" # the base hostname & protocol for your site
paginate: 5 # The number of posts to show per page on your homepage

# Social
facebook: thiagoevan
twitter: thiago_evan
github:  kidush

#Additional Pages
about: about

permalink: /:title

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: kidush #github username
repo: hanuman #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  http://thiagoflins.com/
source_url:  https://github.com/kidush/hanuman #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
